"""empty message

Revision ID: 509ca97d70ac
Revises: f629c96c71af
Create Date: 2024-10-14 22:24:39.976952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509ca97d70ac'
down_revision = 'f629c96c71af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_fav')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fav',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planetas_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], name='user_fav_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], name='user_fav_planetas_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_fav_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_fav_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
